### =============================================
### LOCALHOST ENVIRONMENT
### =============================================

### Get all movies
GET http://localhost:8080/movies

### Get movie by id
GET http://localhost:8080/movies/69c6b1cd6d12fe9874a3b141

### Create movie
POST http://localhost:8080/movies HTTP/1.1
content-type: application/json

{
    "firstName":"James",
    "lastName":"Brown",
    "email":"jbrown@test.com",
    "favoriteColor":"Black",
    "birthday":"02/17/1936"
}

### PUT movie
PUT http://localhost:8080/movies/69c66e540df2bdaf3017a135 HTTP/1.1
content-type: application/json

{
    "firstName":"James",
    "lastName":"Brown",
    "email":"jbrown@test.com",
    "favoriteColor":"Brown",
    "birthday":"02/17/1936"
}

### DELETE movie
DELETE http://localhost:8080/movies/69c673658f40941096a9b902 HTTP/1.1

### =============================================
### RENDER PRODUCTION ENVIRONMENT
### =============================================

# Define the Base URL
@baseUrl = https://cse341rmr-api.onrender.com

# =============================================
# API Endpoints
# =============================================

### Get All Items
GET {{baseUrl}}/movies HTTP/1.1

### Get movie by id
GET {{baseUrl}}/movies/69c6b1cd6d12fe9874a3b141 HTTP/1.1